"""add users table

Revision ID: 1ba7a70153e2
Revises: 9a90395dc48
Create Date: 2015-07-18 19:45:16.010666

"""

# revision identifiers, used by Alembic.
revision = '1ba7a70153e2'
down_revision = '9a90395dc48'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('req_id_creator', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['req_id_creator'], ['requests.req_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username', name='username_is_unique')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    ### end Alembic commands ###
