"""add measurement comment field

Revision ID: 25a002eb2ce4
Revises: 35f6087a7f10
Create Date: 2015-09-28 01:43:46.768256

"""

# revision identifiers, used by Alembic.
revision = '25a002eb2ce4'
down_revision = '35f6087a7f10'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('comment', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements', 'comment')
    ### end Alembic commands ###
