"""update empty event type table

Revision ID: 2f05e372f95a
Revises: 4014bccd156
Create Date: 2015-08-08 13:57:38.101576

"""

# revision identifiers, used by Alembic.
revision = '2f05e372f95a'
down_revision = '4014bccd156'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_types', sa.Column('trigger_id', sa.Integer(), nullable=True))
    op.drop_index('ix_event_types_next_trigger', table_name='event_types')
    op.create_foreign_key(None, 'event_types', 'triggers', ['trigger_id'], ['trigger_id'])
    op.drop_column('event_types', 'next_trigger')
    op.drop_column('event_types', 'mean_inactive_delay')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_types', sa.Column('mean_inactive_delay', postgresql.INTERVAL(), autoincrement=False, nullable=False))
    op.add_column('event_types', sa.Column('next_trigger', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'event_types', type_='foreignkey')
    op.create_index('ix_event_types_next_trigger', 'event_types', ['next_trigger'], unique=False)
    op.drop_column('event_types', 'trigger_id')
    ### end Alembic commands ###
