"""add index and uniqueness constraint for key

Revision ID: 35f6087a7f10
Revises: 874e26a6016
Create Date: 2015-09-28 01:34:34.541430

"""

# revision identifiers, used by Alembic.
revision = '35f6087a7f10'
down_revision = '874e26a6016'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_measured_var_units_unit_key'), 'measured_var_units', ['unit_key'], unique=False)
    op.create_unique_constraint('key_is_unique_within_measured_var', 'measured_var_units', ['measured_var_id', 'unit_key'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('key_is_unique_within_measured_var', 'measured_var_units', type_='unique')
    op.drop_index(op.f('ix_measured_var_units_unit_key'), table_name='measured_var_units')
    ### end Alembic commands ###
