"""remove symmetric FK

Revision ID: 4014bccd156
Revises: 53046aa18bde
Create Date: 2015-08-08 02:24:23.591916

"""

# revision identifiers, used by Alembic.
revision = '4014bccd156'
down_revision = '53046aa18bde'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'triggers_survey_question_id_fkey', 'triggers', type_='foreignkey')
    op.drop_column('triggers', 'survey_question_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('triggers', sa.Column('survey_question_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'triggers_survey_question_id_fkey', 'triggers', 'survey_questions', ['survey_question_id'], ['sq_id'])
    ### end Alembic commands ###
