"""add timestamp column to event types

Revision ID: 43a2b49634d1
Revises: 2f05e372f95a
Create Date: 2015-08-08 15:41:12.677313

"""

# revision identifiers, used by Alembic.
revision = '43a2b49634d1'
down_revision = '2f05e372f95a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_types', sa.Column('timestamp', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_types', 'timestamp')
    ### end Alembic commands ###
