"""initial schema for requests table

Revision ID: 9a90395dc48
Revises: 
Create Date: 2015-07-18 17:08:11.885036

"""

# revision identifiers, used by Alembic.
revision = '9a90395dc48'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('req_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('server_version', sa.String(), nullable=True),
    sa.Column('client_ip', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('referer', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('req_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    ### end Alembic commands ###
